# Generated by Django 5.0.6 on 2024-05-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
