# Generated by Django 5.0.6 on 2024-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="levi.jpeg", upload_to=""),
        ),
    ]
