# Generated by Django 5.0.6 on 2024-05-28 22:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0011_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="media/avatar.jpeg", max_length=255, verbose_name="image"
            ),
        ),
    ]
