# Generated by Django 5.0.6 on 2024-05-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0017_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="avatar.jpeg", upload_to="profile_img"),
        ),
    ]
