name: Django Deployment

on:
  push:
    branches:
      - main  # Ajusta el nombre de la rama si es necesario

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        pipenv shell

    - name: Run Tests
      run: |
        python manage.py test  social

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway run python manage.py migrate
        railway run python manage.py collectstatic
