name: Deploy django-social-network

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
  - name: checkout repo
    uses: actions/checkout@v4
  
  - name: set up python
    uses: actions/setup-python@v5
    with:
        python-version: '3.11'

  - name: Install dependencies
    run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
  - name: Run tests
    run: |
      python manage.py test social

  - name: Deploy on Railway
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    run: |
      railway run python manage.py migrate
      railway run python manage.py collectstatic --noinput 
